apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  labels:
    app: todo
  namespace: todo-app
spec:
  type: ClusterIP
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001

