apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  namespace: todo-app
spec:
  type: LoadBalancer
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
